### ISSUE TITLE
Accelerating control

### ISSUE THREAD

**Issue by kineticsystem** [tocttou/three-freeform-controls#41] opened 2022-03-10 23:11 UTC
Hi there. I think I found a bug in the component. If you put the controller at the right pose (I haven't figured out what right the pose is) the component behaves erratically. Most of the time it speeds up out of control. In attachment, a video showing the issue reproduced by playing with the following example: https://ashishchaudhary.in/three-freeform-controls/examples/different-anchors-different-objects

![bug](https://user-images.githubusercontent.com/5970998/157770267-753ef05a-4286-4109-b042-ffd4c29cc1ab.gif)

**Comment by kineticsystem** [comment] 2022-03-25 00:53
The math you have used while translating along an axis is incorrect. As per following document, when translating along an axis you should use the closest point on the translation axis ray to the camera ray:
https://ed.ilogues.com/2018/06/27/translate-rotate-and-scale-manipulators-in-3d-modelling-programs
I forked your github repo and fixed the issue refactoring the raycaster.ts file:
https://github.com/kineticsystem/three-freeform-controls

**Comment by Barsovich** [comment] 2022-08-20 09:06
Thank you so much for your solution. It works wonderful!

I also found a problem about rotations that if you rotate the object when you are looking at the rotation handle from almost the side, it can apply a completely different rotation that is not possible by any rotating the object around that axis. I suspect that it can be a numerical issue caused by the active plane and the eye normal being almost parallel to each other and the drag actions being very large but didn't have a chance to debug it properly.

**Comment by tocttou** [comment] 2023-02-28 20:26
Thanks for the changes @Barsovich. I have merged the [PR](https://github.com/tocttou/three-freeform-controls/pull/42) and made a new release.

**Comment by tocttou** [comment] 2023-02-28 20:27
@Barsovich could you please create a new Github issue if you are still facing the issue you mentioned?

**Closed by tocttou** 2023-02-28 20:27 UTC
